//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Business.Components.PublisherService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Common.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bank.Business.Components.PublisherService.SendEmailMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bank.Business.Components.PublisherService.TransferMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bank.Business.Components.PublisherService.TransferResultMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bank.Business.Components.PublisherService.SubmitDeliveryMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bank.Business.Components.PublisherService.DeliverProcessedMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bank.Business.Components.PublisherService.DeliverCompleteMessage))]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendEmailMessage", Namespace="http://schemas.datacontract.org/2004/07/Common.Model")]
    [System.SerializableAttribute()]
    public partial class SendEmailMessage : Bank.Business.Components.PublisherService.Message {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAddressesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddresses {
            get {
                return this.ToAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAddressesField, value) != true)) {
                    this.ToAddressesField = value;
                    this.RaisePropertyChanged("ToAddresses");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferMessage", Namespace="http://schemas.datacontract.org/2004/07/Common.Model")]
    [System.SerializableAttribute()]
    public partial class TransferMessage : Bank.Business.Components.PublisherService.Message {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pFromAcctNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pToAcctNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pAmount {
            get {
                return this.pAmountField;
            }
            set {
                if ((this.pAmountField.Equals(value) != true)) {
                    this.pAmountField = value;
                    this.RaisePropertyChanged("pAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pFromAcctNumber {
            get {
                return this.pFromAcctNumberField;
            }
            set {
                if ((this.pFromAcctNumberField.Equals(value) != true)) {
                    this.pFromAcctNumberField = value;
                    this.RaisePropertyChanged("pFromAcctNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pToAcctNumber {
            get {
                return this.pToAcctNumberField;
            }
            set {
                if ((this.pToAcctNumberField.Equals(value) != true)) {
                    this.pToAcctNumberField = value;
                    this.RaisePropertyChanged("pToAcctNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferResultMessage", Namespace="http://schemas.datacontract.org/2004/07/Common.Model")]
    [System.SerializableAttribute()]
    public partial class TransferResultMessage : Bank.Business.Components.PublisherService.Message {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitDeliveryMessage", Namespace="http://schemas.datacontract.org/2004/07/Common.Model")]
    [System.SerializableAttribute()]
    public partial class SubmitDeliveryMessage : Bank.Business.Components.PublisherService.Message {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryNotificationAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryNotificationAddress {
            get {
                return this.DeliveryNotificationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryNotificationAddressField, value) != true)) {
                    this.DeliveryNotificationAddressField = value;
                    this.RaisePropertyChanged("DeliveryNotificationAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationAddress {
            get {
                return this.DestinationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationAddressField, value) != true)) {
                    this.DestinationAddressField = value;
                    this.RaisePropertyChanged("DestinationAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceAddress {
            get {
                return this.SourceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceAddressField, value) != true)) {
                    this.SourceAddressField = value;
                    this.RaisePropertyChanged("SourceAddress");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliverProcessedMessage", Namespace="http://schemas.datacontract.org/2004/07/Common.Model")]
    [System.SerializableAttribute()]
    public partial class DeliverProcessedMessage : Bank.Business.Components.PublisherService.Message {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid pDeliveryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMsgField, value) != true)) {
                    this.errorMsgField = value;
                    this.RaisePropertyChanged("errorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.orderNumberField, value) != true)) {
                    this.orderNumberField = value;
                    this.RaisePropertyChanged("orderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid pDeliveryId {
            get {
                return this.pDeliveryIdField;
            }
            set {
                if ((this.pDeliveryIdField.Equals(value) != true)) {
                    this.pDeliveryIdField = value;
                    this.RaisePropertyChanged("pDeliveryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliverCompleteMessage", Namespace="http://schemas.datacontract.org/2004/07/Common.Model")]
    [System.SerializableAttribute()]
    public partial class DeliverCompleteMessage : Bank.Business.Components.PublisherService.Message {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid pDeliveryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid pDeliveryId {
            get {
                return this.pDeliveryIdField;
            }
            set {
                if ((this.pDeliveryIdField.Equals(value) != true)) {
                    this.pDeliveryIdField = value;
                    this.RaisePropertyChanged("pDeliveryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublisherService.IPublisherService")]
    public interface IPublisherService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPublisherService/Publish")]
        void Publish(Bank.Business.Components.PublisherService.Message pMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublisherServiceChannel : Bank.Business.Components.PublisherService.IPublisherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublisherServiceClient : System.ServiceModel.ClientBase<Bank.Business.Components.PublisherService.IPublisherService>, Bank.Business.Components.PublisherService.IPublisherService {
        
        public PublisherServiceClient() {
        }
        
        public PublisherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublisherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Publish(Bank.Business.Components.PublisherService.Message pMessage) {
            base.Channel.Publish(pMessage);
        }
    }
}
